stages:
  - backend
  - frontend

backendlint:
  stage: backend
  script:
    - cd backend
    # - dnf install -y python37
    # - python3.7 -mensurepip
    # - dnf install -y mariadb-server mariadb-devel
    # - dnf install -y git
    # - dnf install -y gcc libffi-devel python3-devel openssl-devel
    # - pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
    # - pip3 install pylint
    # - pip3 install pylint-django
    # - pylint --rcfile=.pylintrc ./**/*.py || exit $((35 & $?))
  allow_failure: false
  tags:
    - txy3

backendtest:
  stage: backend
  script:
    - cd backend
    # - dnf install -y python37
    # - python3.7 -mensurepip
    # - dnf install -y mariadb-server mariadb-devel
    # - dnf install -y git
    # - dnf install -y gcc libffi-devel python3-devel openssl-devel
    # - pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
    # - python3  manage.py test
  allow_failure: false 
  tags:
    - txy2

frontendlint:
  stage: frontend
  script:
    - cd frontend
    - dnf -y install nodejs npm
    - npm install --registry https://registry.npm.taobao.org
    - npm run eslint
    # - npm run stylelint
  allow_failure: false
  tags:
    - txy3

frontendtest:
  stage: frontend
  script:
    - cd frontend
    - dnf -y install nodejs npm
    - npm install --registry https://registry.npm.taobao.org
    - npm run test
  allow_failure: false
  tags:
    - txy2



